### ISSUE TITLE
与软件有冲突

### ISSUE THREAD

**Issue by chinapsk** [heinsega/OX163#3]
软件和REA EMT and PARAMEDIC TEST SOFTWEAR(PERMIUM）版本有严重冲突，一旦开启OX163就会弹出前述软件的安装界面，并且ox163将不会进入下一步的窗口，如需此软件镜像请联系我以便用于测试。望尽快修复谢谢

**Comment by heinsega** [comment]
windows installer问题，非本软件问题。
参看http://www.ugschina.com/forum/forumTopicRead.asp?id=1772
